### PR TITLE
Add classes for handling HTTP Requests using Netty

### PR DESCRIPTION
**Pull request by yasithdev**
## Description
Added `netty` module into microservices pom file. Add the following packages and classes into it
* `uri`
    * `PathPattern` - Store the JAX-RS annotated Path as a regex for easy lookup
    * `PathMatch` - Stores the matched PathParams and their values for a given URI
* `routing`
    * `MethodWrapper` - Wrap a JAX-RS annotated Method so that it can be executed by passing the Request Parameters
    * `Router` - To Map a PathPattern to a MethodWrapper
    * `RoutingResult` - Stores the `PathMatch` and `MethodWrapper` match for a routing result.
* `util`
    * `Reflector` - Helper class to get JAX-RS annotations from a class
* `FullHttpRequestHandler` - Accept a `FullHttpRequest` object, find the correct request handler through `Router` instance, and execute the handler method in `MethodWrapper`
* `NettyApplication` - Extends `MicroserviceApplication` and is the starting point for microservices
* `NettyServer` - Stores the Netty Configurations and the pipelines that should be registered to provide HTTP request handling using Netty.

### Dependencies added
```
<!-- Netty Transport -->
<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-transport</artifactId>
	<version>4.1.19.Final</version>
	<scope>compile</scope>
</dependency>

<!-- Netty Codec for HTTP -->
<dependency>
	<groupId>io.netty</groupId>
	<artifactId>netty-codec-http</artifactId>
	<version>4.1.19.Final</version>
	<scope>compile</scope>
</dependency>
```

## Type of change
Feature Addition
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
No tests were written at this point.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by randilfernando — APPROVED** [review]
I approve this feature

**Comment by randilfernando** [comment]
Codacy review show some errors but those lines are needed for further implementation. What are we going to do about that?

**Comment by yasithdev** [comment]
I have yet to figure out how to map the HTTP URL in the request to the Handler’s path, and create objects with PathParams assigned.. Do u have an idea on how to do that?

**Comment by yasithdev** [comment]
I implemented the route registration. NettyApplication should be working now afaik.

**Pull request merged**
